<?php
include_once('inc/postcodechacking.php');
include_once('inc/orien_con.php');
include_once('inc/all_equation.php');

header('Content-type: text/javascript');
	
if($_POST['action'] == 'solarcalc_lookup_postcode'){
	
	echo json_encode($jsonpost);
	
		}else{		
		echo '{"type":"success","msg":"","withoutSolarBill":'.floor($billsyearforyears).',"withSolarBill":'.floor($billswiyearforyears).',"savings":'.floor($saveyearforyears).',"graphMax":'.floor($graphmax).',"graphMin":'.floor($graphmin).',"chart":{"bills":{"'.$year1.'":'.floor($billsyear1).',"'.$year2.'":'.floor($billsyear2).',"'.$year3.'":'.floor($billsyear3).',"'.$year4.'":'.floor($billsyear4).',"'.$year5.'":'.floor($billsyear5).',"'.$year6.'":'.floor($billsyear6).',"'.$year7.'":'.floor($billsyear7).',"'.$year8.'":'.floor($billsyear8).',"'.$year9.'":'.floor($billsyear9).',"'.$year10.'":'.floor($billsyear10).',"'.$year11.'":'.floor($billsyear11).',"'.$year12.'":'.floor($billsyear12).',"'.$year13.'":'.floor($billsyear13).',"'.$year14.'":'.floor($billsyear14).',"'.$year15.'":'.floor($billsyear15).',"'.$year16.'":'.floor($billsyear16).',"'.$year17.'":'.floor($billsyear17).',"'.$year18.'":'.floor($billsyear18).',"'.$year19.'":'.floor($billsyear19).',"'.$year20.'":'.floor($billsyear20).'},"solar":{"'.$year1.'":'.floor($billswiyear1).',"'.$year2.'":'.floor($billswiyear2).',"'.$year3.'":'.floor($billswiyear3).',"'.$year4.'":'.floor($billswiyear4).',"'.$year5.'":'.floor($billswiyear5).',"'.$year6.'":'.floor($billswiyear6).',"'.$year7.'":'.floor($billswiyear7).',"'.$year8.'":'.floor($billswiyear8).',"'.$year9.'":'.floor($billswiyear9).',"'.$year10.'":'.floor($billswiyear10).',"'.$year11.'":'.floor($billswiyear11).',"'.$year12.'":'.floor($billswiyear12).',"'.$year13.'":'.floor($billswiyear13).',"'.$year14.'":'.floor($billswiyear14).',"'.$year15.'":'.floor($billswiyear15).',"'.$year16.'":'.floor($billswiyear16).',"'.$year17.'":'.floor($billswiyear17).',"'.$year18.'":'.floor($billswiyear18).',"'.$year19.'":'.floor($billswiyear19).',"'.$year20.'":'.floor($billswiyear20).'},"savings":{"'.$year1.'":'.floor($saveyear1).',"'.$year2.'":'.floor($saveyear2).',"'.$year3.'":'.floor($saveyear3).',"'.$year4.'":'.floor($saveyear4).',"'.$year5.'":'.floor($saveyear5).',"'.$year6.'":'.floor($saveyear6).',"'.$year7.'":'.floor($saveyear7).',"'.$year8.'":'.floor($saveyear8).',"'.$year9.'":'.floor($saveyear9).',"'.$year10.'":'.floor($saveyear10).',"'.$year11.'":'.floor($saveyear11).',"'.$year12.'":'.floor($saveyear12).',"'.$year13.'":'.floor($saveyear13).',"'.$year14.'":'.floor($saveyear14).',"'.$year15.'":'.floor($saveyear15).',"'.$year16.'":'.floor($saveyear16).',"'.$year17.'":'.floor($saveyear17).',"'.$year18.'":'.floor($saveyear18).',"'.$year19.'":'.floor($saveyear19).',"'.$year20.'":'.floor($saveyear20).'}},"effPriceKilowatt":'.floor($effpricekilowatt).',"solarProduction":'.floor($totalpro).',"solarFeedInPercentage":'.floor($feedinPercentage).',"solarFeedIn":'.floor($fedback).',"powerSavings":'.floor($savingonpb).',"payback":'.substr($payback, 0, 3).',"roi":'.substr($roi, 0, 4).',"unitsPerDay":'.floor($pardaypro).'}';
	}
?>