<?php
/**
 * Main file of social buttons module. This modules has following components:
 * - Social media profiles for whole website, which are displayed in Header and Contact page
 * - Settings for social buttons, which are displayed in posts, pages, archive pages, etc.
 *
 * Settings for social buttons are separated in 2 parts:
 * - 1 settings page under 7listings menu
 * - Design settings in theme's Design Advanced page
 * - Design settings in Contact page
 *
 * To isolate this module into a plugin, we need to:
 *
 * - Move JS file from theme folder 'js' to the plugin
 * - Create a CSS file contains all styles, separated from theme
 * - Copy 'twitter-api-php.php' from theme 'widgets' folder to plugin folder
 * - Move shortcode popup from theme 'shortcode/popup' folder to plugin folder
 *
 * Regarding CSS: think about custom color scheme for social buttons, because it's generated by LESS
 */

define( 'SSB_DIR', plugin_dir_path( __FILE__ ) );

// Counter library, used both in admin (via ajax) and frontend
require SSB_DIR . 'inc/counter.php';

if ( is_admin() )
{
	// Ajax actions
	if ( defined( 'DOING_AJAX' ) && DOING_AJAX )
	{
		require SSB_DIR . 'inc/admin/ajax.php';
		Sl_Social_Buttons_Ajax::load();
	}
	// Normal admin actions
	else
	{
		// Design settings
		require SSB_DIR . 'inc/admin/design-settings.php';
		Sl_Social_Buttons_Design_Settings::load();

		// Social Media settings page
		require SSB_DIR . 'inc/admin/settings.php';
		new Sl_Settings_Social( 'social', __( 'Social Media', '7listings' ) );
		
		// Knowledge Graph settings page
		require SSB_DIR . 'inc/admin/knowledge-graph.php';
		new Sl_Knowledge_Graph( 'knowledge-graph', __( 'Knowledge Graph', '7listings' ) );
	}
}
else
{
	require SSB_DIR . 'inc/share-buttons.php';

	require SSB_DIR . 'inc/shortcode.php';
	new Sl_Social_Buttons_Shortcode;

	require SSB_DIR . 'inc/frontend.php';
	new Sl_Social_Buttons_Frontend;
}

add_filter( 'sl_default_settings', 'sl_social_buttons_default_settings' );

/**
 * Setup default settings for social buttons
 *
 * @param array $settings Default theme settings
 *
 * @return array
 */
function sl_social_buttons_default_settings( $settings )
{
	$settings = array_merge( array(
		// Design settings for social links in header
		'design_header_social_display' => 1,
		'design_header_social_color'   => '#f00',
		'design_header_social_counter' => 1,

		// Settings for social links in contact page
		'contact_social_links'         => 1,
		'contact_social_counter'       => 1,
		'design_contact_social_color'  => '#f00',

		// Design settings for social buttons
		'design_social_icon_color'     => '#f00',
		'design_social_icon_counter'   => 1,

		// Button settings
		'social_buttons'               => array(),
	), $settings );

	// Button settings
	$settings['social_buttons'] = array_merge( array(
		'buttons'  => array(),
		'show_on'  => array(),
		'position' => 'bottom',
	), $settings['social_buttons'] );

	return $settings;
}

add_action( 'widgets_init', 'sl_social_buttons_register_widget' );

/**
 * Register social links widget
 *
 * @return void
 */
function sl_social_buttons_register_widget()
{
	// Register widget
	require SSB_DIR . 'inc/widget-social-links.php';

	register_widget( 'Sl_Widget_Social_Links' );
}
