<?php $post_type = 'tour'; ?>

<div class="section">

	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Bookings', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Enable online booking functionality. If OFF listings display without a booking button like a catalog.', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<?php Sl_Form::checkbox( $post_type . '_booking' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'If "ON", please fill Payment details', '7listings' ) . '" type="message"]<span class="icon"></span>[/tooltip]' ); ?>
		</div>
	</div>

	<br>

	<h3><?php _e( 'Menu', '7listings' ); ?></h3>

	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Title', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Top level menu item text, for autogenerated menu', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<input type="text" name="<?php echo THEME_SETTINGS . "[{$post_type}_menu_title]"; ?>" value="<?php echo sl_setting( "{$post_type}_menu_title" ); ?>" class="sl-input-medium">
		</div>
	</div>
	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Dropdown', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Sorting options for dropdown<br>in main nav.', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<select type="text" name="<?php echo THEME_SETTINGS . "[{$post_type}_menu_dropdown]"; ?>" class="sl-input-small">
				<?php
				Sl_Form::options( sl_setting( "{$post_type}_menu_dropdown" ), array(
					'types'     => __( 'Types', '7listings' ),
					'features'  => __( 'Features', '7listings' ),
					'locations' => __( 'Locations', '7listings' ),
				) );
				?>
			</select>
		</div>
	</div>

	<br><br>

	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Featured Graphics', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Display labels for starred and featured listings.', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<?php Sl_Form::checkbox( $post_type . '_featured_graphics' ); ?>
		</div>
	</div>
	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Pages', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Configure your Tour pages templates.', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<?php printf( __( '<a href="%s">Archive settings</a>', '7listings' ), admin_url( 'edit.php?post_type=page&page=tour#archive' ) ); ?>
			<br>
			<?php printf( __( '<a href="%s">Single settings</a>', '7listings' ), admin_url( 'edit.php?post_type=page&page=tour#single' ) ); ?>
		</div>
	</div>

	<br><br>

	<h3><?php _e( 'Advanced', '7listings' ); ?></h3>

	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Label', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Displayed in admin and front; enter in singular. Used when you want to use the tour listings as lessons.', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<input type="text" name="<?php echo THEME_SETTINGS . "[{$post_type}_label]"; ?>" value="<?php echo sl_setting( "{$post_type}_label" ); ?>" class="sl-input-medium">
		</div>
	</div>
	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Permalinks', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Set your url structure for tours.', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<?php printf( __( '<a href="%s">Permalink Settings</a>', '7listings' ), admin_url( 'options-permalink.php' ) ); ?>
		</div>
	</div>
	<br>
	<div class="sl-settings">
		<div class="sl-label">
			<label><?php _e( 'Multiplier', '7listings' ); ?><?php echo do_shortcode( '[tooltip content="' . __( 'Option to use: (Upsells x Guests) useful if one upsell needs to be applied to all guests in booking', '7listings' ) . '" type="info"]<span class="icon"></span>[/tooltip]' ); ?></label>
		</div>
		<div class="sl-input">
			<?php Sl_Form::checkbox( $post_type . '_multiplier' ); ?>
		</div>
	</div>
</div>
